name: walmart_sales_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas=2.3.0
  - scikit-learn=1.6.1
  - mlflow=2.22.0
  - numpy=2.2.6
  - matplotlib=3.10.3
  - scipy=1.15.3
  - pillow=11.2.1 # Umumnya diinstal dengan matplotlib
  - pyarrow=19.0.1
 