name: CI for MLflow Project

on:
  push:
    branches:
      - master # Trigger workflow every time there's a push to the 'master' branch

jobs:
  train_model:
    runs-on: ubuntu-latest # Run the job on the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Fetch the code from the repository

    - name: Setup Miniconda and Create Environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        python-version: 3.10.0 # Make sure this matches your conda.yaml
        auto-update-conda: true
        use-mamba: true # Using mamba often speeds up environment creation
        # Crucial change: Point directly to your conda.yaml file
        environment-file: MLProject/conda.yaml # Path to your conda environment file
        # We don't need to manually activate or add to path if using environment-file
        # auto-activate-base: false
        # activate-environment: "false"
        # add-to-path: true

    - name: Run MLflow Project
      # The 'environment-file' in setup-miniconda should activate the environment automatically.
      # So, we can directly run mlflow.
      # If you encounter "mlflow not found", then try:
      # shell: bash -l {0}
      # run: |
      #   conda activate walmart_sales_env
      #   mlflow run .
      run: mlflow run . # Run the MLflow project
      working-directory: MLProject # Ensure commands run within the MLProject folder

    # Optional: Step to upload artifacts or results
    - name: Upload MLflow Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: MLProject/mlruns/ # MLflow stores runs in the mlruns/ folder by default