name: CI for MLflow Project

on:
  push:
    branches:
      - master # Trigger workflow setiap ada push ke branch 'master'

jobs:
  train_model:
    runs-on: ubuntu-latest # set up job

    steps:
    - name: Run actions/checkout@v3 # Mengambil kode dari repositori
      uses: actions/checkout@v4 # Menggunakan v4, kompatibel dengan v3

    - name: Set up Python 3.12.7 # Setup Miniconda dan versi Python
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        python-version: 3.12.7
        auto-update-conda: true
        use-mamba: true
        auto-activate-base: false
        add-to-path: true

    - name: Check Env # Debug: List Existing Conda Environments
      shell: bash -l {0}
      run: |
        echo "Listing all known conda environments:"
        conda info --envs

    - name: Install dependencies # Membuat dan menginstal dependensi Conda Environment
      shell: bash -l {0}
      run: |
        echo "Creating conda environment 'walmart_sales_env' from conda.yaml..."
        conda env create -f conda.yaml
        echo "Conda environment creation finished successfully."
      working-directory: MLProject

    - name: Run mlflow project
      shell: bash -l {0}
      run: |
        echo "Running training script with MLflow logging..."
        # Tidak perlu mengatur MLFLOW_TRACKING_URI di sini karena modelling.py sudah mengaturnya
        conda run -n walmart_sales_env python modelling.py
        echo "Training script execution finished."
      working-directory: MLProject # Tetap jalankan python di sini agar path ke modelling.py benar

    - name: Get latest MLflow run_id
      id: get_run_id
      # working-directory: MLProject # TIDAK DIPERLUKAN LAGI UNTUK PENCARIAN MLRUNS
      run: |
        # Cari direktori run terbaru di /tmp/mlruns/, BUKAN di MLProject/mlruns/
        LATEST_RUN_DIR=$(find /tmp/mlruns/ -maxdepth 2 -type d -name "*-*-*-*-*" | sort -r | head -n 1)

        if [ -z "$LATEST_RUN_DIR" ]; then
          echo "No MLflow run directory found in /tmp/mlruns/."
          exit 1
        fi

        LATEST_RUN_ID=$(basename "$LATEST_RUN_DIR")
        echo "Found latest MLflow run ID: $LATEST_RUN_ID"
        echo "run_id=$LATEST_RUN_ID" >> $GITHUB_OUTPUT

    - name: Upload MLflow Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        # PENTING: Ubah path ini agar sesuai dengan /tmp/mlruns
        path: /tmp/mlruns/
