name: CI for MLflow Project

on:
  push:
    branches:
      - main # Trigger workflow setiap ada push ke branch 'main'

jobs:
  train_model:
    runs-on: ubuntu-latest # Jalankan di runner Ubuntu terbaru

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Mengambil kode dari repositori

    - name: Setup Miniconda and Create Environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        python-version: 3.9 # Make sure this matches your conda.yaml
        auto-update-conda: true
        use-mamba: true
        environment-file: MLProject/conda.yaml # Path to your conda environment file
        # Kita akan mengaktifkan environment secara manual di step berikutnya
        # auto-activate-base: false
        # activate-environment: "false"
        # add-to-path: true # Ini sudah default true, tapi kita bisa eksplisit

    - name: Run MLflow Project
      # Ini adalah bagian terpenting untuk memastikan conda env aktif sepenuhnya
      shell: bash -l {0} # Force login shell untuk inisialisasi conda yang benar
      run: |
        echo "Activating conda environment: walmart_sales_env"
        conda activate walmart_sales_env
        echo "Running MLflow project..."
        mlflow run . # Perintah untuk menjalankan MLflow Project
        echo "MLflow project run completed."
      working-directory: MLProject # Pastikan perintah ini dijalankan di dalam folder MLProject

    # Opsional: Langkah untuk mengunggah artefak atau hasil
    - name: Upload MLflow Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: MLProject/mlruns/ # MLflow stores runs in the mlruns/ folder by default