name: CI for MLflow Project

on:
  push:
    branches:
      - master  # Trigger setiap push ke master

jobs:
  train_model:
    runs-on: ubuntu-latest  # Set up job

    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3  # Checkout source code

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.7

      - name: Check Env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        working-directory: MLProject
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run MLflow project
        working-directory: MLProject
        run: |
          python modelling.py

      - name: Get latest MLflow run_id
        working-directory: MLProject
        run: |
          latest_run=$(ls -td mlruns/*/* | head -n 1)
          echo "Latest run directory: $latest_run"
